# Generated by Django 4.0.1 on 2022-01-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_endpoint', models.URLField(blank=True, null=True)),
                ('test_name', models.CharField(max_length=255)),
                ('result', models.BooleanField()),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('exception', models.CharField(blank=True, max_length=255, null=True)),
                ('test_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
