# Generated by Django 4.0.1 on 2022-01-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_manager_testdrive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlog',
            name='json_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testlog',
            name='json_validation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testlog',
            name='link_checker',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testlog',
            name='request_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testlog',
            name='status_code',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testlog',
            name='result',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testlog',
            name='test_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
