# Generated by Django 4.0.1 on 2022-01-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_manager_testdrive', '0002_testlog_json_response_testlog_json_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlog',
            name='json_payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
